### ISSUE TITLE
Update Lock Files

### ISSUE THREAD

**Issue by dbanty** [knope-dev/knope#162]
Right now, only the metadata file (`Cargo.toml`, `pyproject.toml`, `package.json`) is updated and not the equivalent lockfile (`cargo.lock`, `poetry.lock`, `package-lock.json`) (the last one might not keep the package version). This leaves inconsistencies that will get updated the next time a user does anything with the package which is less than ideal.

Any supported package manager (so Cargo, Poetry, and NPM right now) should not leave any work to-do after bumping a version.

**Comment by FallenValkyrie** [comment]
For anyone running into it, here's a workaround:

after each `PrepareRelease`, run `cargo build, before commiting. 

This should prevent it from ever desynchronizing until this issue is fixed.

**Comment by BatmanAoD** [comment]
For a more minimal command that won't update your dependencies, try `cargo update -w`.

**Comment by dbanty** [comment]
0.18.0 will have support for `Cargo.lock` 🥳. We can open new issues for additional lock file formats
