### ISSUE TITLE
Git Add files in `PrepareRelease`

### ISSUE THREAD

**Issue by dbanty** [knope-dev/knope#215]
The `PrepareRelease` step could add and commit any modified files to save some effort for users. If they need more files, they can `commit --amend` afterward, but usually (hopefully) this won't be necessary. Then, the `Release` step should shell out to `git push` (`git2` can't do this very well).

A `skip_commit` option should be added to `PrepareRelease` to allow users to opt-out of this behavior.

**Comment by Shadow53** [comment]
Alternatively, it could follow what IDEs do (at least the Jetbrains ones) and just `git add` the files without committing. I think this would be preferable to `git commit --amend`
