### ISSUE TITLE
Tell users which file did not exist when a required file is missing

### ISSUE THREAD

**Issue by Shadow53** [knope-dev/knope#234]
I was running `knope` for the first time on an untagged repository and got the following error:

```
Error: step::io_error

  × I/O error
  ╰─▶ No such file or directory (os error 2)
  help: This occurred during a step that requires reading or writing to... something. The problem could be a network issue or a file permission issue.
```

I had to enable debug output to get enough context to figure out that it was erroring because `CHANGELOG.md` did not exist. There's two bugs here, I think:

1. The error message should, when possible, include the path that does not exist
2. `CHANGELOG.md` should be created when it does not already exist

**Comment by dbanty** [comment]
Pretty sure this is just a wrapper on std::io::Error which… rarely has useful info 😬. We should replace that with more specific errors (e.g., FileNotFound) that have useful context.

Creating a changelog if it doesn’t already exist does sound like a useful feature, also. Thanks!

**Comment by Shadow53** [comment]
Regarding error paths, this also applies to `step::invalid_cargo_toml`, where I have multiple `Cargo.toml` files and no indication which one is the problem.
