### ISSUE TITLE
missingTaggerEntry: invalid format - expected 'tagger' line

### ISSUE THREAD

**Issue by Shadow53** [knope-dev/knope#235]
I ran a prerelease flow on my local machine and got the following warning *after* the flow pushed to GitLab using `git push --tags`:

```
remote: warning: object 5db1ec4859c7017d2a1d955262abc09213ad5ef9: missingTaggerEntry: invalid format - expected 'tagger' line
```

I am unsure what the exact cause was, but my suspicion is that it was part of the `Release` flow.

The current flow is:

- `PrepareRelease { prerelease_label = "rc" }`
- `Command` (update Cargo workspace packages, `git add/commit` files modified by previous step)
- `Release`
- `Command: git push && git push --tags`

**Comment by dbanty** [comment]
🤔what does that warning even mean?

Something wrong with the way that `Release` is creating tags most likely, right? In which case it will probably be solved by #231

**Comment by Shadow53** [comment]
> 🤔what does that warning even mean?

I couldn't find any information with a quick search, so I don't know.

> Something wrong with the way that Release is creating tags most likely, right? In which case it will probably be solved by https://github.com/knope-dev/knope/issues/231

Maybe as a side effect? There isn't a segfault, since I built from source.

**Comment by dbanty** [comment]
https://gitlab.com/gitlab-org/gitlab-foss/-/issues/27228 looks to be related.

**Comment by dbanty** [comment]
Looks like we need to pass a parameter as `tagger` [here](https://github.com/knope-dev/knope/blob/a8ad1191fdee2e8e9832606703e32780eeee6381/src/releases/git.rs#L28) instead of `None` as some GitLab versions can't handle that (apparently optional) attribute being empty. Now I just need to figure out the easiest way to get a `SignatureRef`.
