### ISSUE TITLE
Mention that this project was renamed from dobby

### ISSUE THREAD

**Issue by asfaltboy** [knope-dev/knope#254]
Hi, thanks for writing knope! I came across this linked from another project, and was not sure for a minute if this is the same project. Would be helpful to give some context around the old and new name in the README and/or the introduction page in the docs, along with any fun facts, like what knope stands for or how to pronounce it :)

**Comment by dbanty** [comment]
I added some notes about the current name to the docs. I'm trying to avoid mentioning the old name since very few projects used it under that name (mostly just ones that I added it to 😁).
