### ISSUE TITLE
Support bumping pyproject.toml project.version

### ISSUE THREAD

**Issue by Shadow53** [knope-dev/knope#271]
Non-poetry Python projects, including `maturin`/`pyo3`-based projects, use `project.version` instead of the poetry-specific path in `pyproject.toml`. This causes issues when using `pyproject.toml` to add metadata to `maturin`-generated wheels, as the version number there does not get bumped.

**Comment by Shadow53** [comment]
Related `poetry` issue to support the PEP(s) providing the field: https://github.com/python-poetry/poetry/issues/3332

**Comment by dbanty** [comment]
0.6.1 coming at you. Thanks!
