### ISSUE TITLE
Knope detects incorrect version from tags

### ISSUE THREAD

**Issue by Shadow53** [knope-dev/knope#322]
The current code seems to assume that `Platform::tags()` returns tags in the correctly sorted order, which it does not. It appears to return the same order as `git tag`, which sorts, e.g. `0.1.0`, `0.10.0`, `0.2.0`.

I've written a fix for this that compares tag versions before deciding that one is a new version, and will open a PR after submitting this issue.

**Comment by dbanty** [comment]
Silly me assuming it would give me the latest git tag 🫠. Thanks for the fix!
