### ISSUE TITLE
Compilation failure/Bump git-repository version

### ISSUE THREAD

**Issue by Shadow53** [knope-dev/knope#384]
Trying to compile `knope 0.7.0` from source (i.e. via `cargo install knope`) fails with the following error:

```
error[E0063]: missing field `expected_checksum` in initializer of `git_index::decode::Options`
  --> /Users/mbryant/.cargo/registry/src/github.com-1ecc6299db9ec823/git-repository-0.33.0/src/repository/worktree.rs:80:13
   |
80 |             git_index::decode::Options {
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `expected_checksum`
```

Since `knope` current uses `git-repository 0.33.0` and the latest is `0.35.0`, I imagine bumping the version would fix the error.

The crate also mentions the below, but I'm not sure if it would cause more issues:

> This crate is now named 'gix' and not available under this name anymore

**Comment by dbanty** [comment]
Should be fixed by #383
