### ISSUE TITLE
Recent glibc dependency

### ISSUE THREAD

**Issue by erichulburd** [knope-dev/knope#403]
I'm using a recipe to install knope using [cargo-binstall](https://github.com/cargo-bins/cargo-binstall) in CICD. The recipe broke for more recent versions of knope.

The following should be reproducible:

```shell
docker run -it python:3.10.9 /bin/bash
curl -o cargo-bininstall.tgz -fsSL https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
tar -xvf cargo-bininstall.tgz
rm cargo-bininstall.tgz
mv cargo-binstall /usr/bin
chmod +x /usr/bin/cargo-binstall
export PATH="$PATH:$HOME/.cargo/bin"
cargo-binstall knope --force --no-confirm
```

That all works but when I try to run a `knope` command I get:

```shell
knope --version
knope: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by knope)
knope: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by knope)
knope: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by knope)
```

However, it works fine if I specify version 0.4.1:

```shell
cargo-binstall knope  --version 0.4.1 --force --no-confirm
```

### Environment

```shell
% uname -a
Darwin xxxx.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64
```

**Comment by dbanty** [comment]
Yuck, GLIBC is the worst. You can use the MUSL build which is fully static to avoid the problem by passing `--targets x86_64-unknown-linux-musl` to `cargo-binstall`. I use the MUSL build in the [GitHub Actions install script](https://github.com/knope-dev/action/blob/609b70ba6ef60cf9a66dffb4b2b8ecb5e41b6ae7/action.yml#L29) as well.

Do you think it'd be worth while to extract that as a shell script for direct installation (for folks who don't need `binstall` for other reasons)?

Also, I wonder if binstall falls back to MUSL—and therefore I should just ditch the GNU builds 🤔

**Comment by dbanty** [comment]
Oh yeah, `cargo-binstall`'s `--help` says "For example, on a 64-bit glibc Linux distribution, the default is to look first for a `x86_64-unknown-linux-gnu` binary, then for a `x86_64-unknown-linux-musl` binary" so I'm just going to stop distributing gnu unless someone comes and asks specifically for it.

**Comment by dbanty** [comment]
0.7.2 will be out shortly and no longer require that `--targets` arg. Anyone who's pinned to an earlier knope version can use that workaround until they can update.

**Comment by erichulburd** [comment]
> Do you think it'd be worth while to extract that as a shell script for direct installation (for folks who don't need binstall for other reasons)?

Shell script installs are awesome as a user - when they work. Can't speak to whether it's worth your effort. I would say if you advertise on the documentation or readme, some good CI coverage for x86 and ARM Linux + Mac (do what you will with Windows) is necessary.

Me personally, I'm happy w/ `binstall`. It's the one install script I need to maintain across several useful tools.
