### ISSUE TITLE
Allow no release

### ISSUE THREAD

**Issue by erichulburd** [knope-dev/knope#416]
If I merge an MR that has a single commit `ci: fix something` and that kicks off a github action/ gitlab task that will run `knope release`, I get the following error:

```
$ knope release
Error: 
  × Problem with workflow release
Error: step::no_release (https://knope-dev.github.io/knope/config/step/PrepareRelease.html)
  × No packages are ready to release
  help: The `PrepareRelease` step will not complete if no commits cause a
        package's version to be increased.
```

The error is clear here, but the behavior isn't necessarily desirable. It would be nice to either:

* Use `knope` to first ask "do I need to run a release?" to preempt running `knope release` or 
* run something like `knope release --allow-no-release` so that the above error isn't thrown

Of course, maybe there's another intent I'm missing!

**Comment by erichulburd** [comment]
I think option 3, which defaults back to option 1 would be most practical for daily use.

I would also consider a Knope configuration value (in root `knope.toml`) that defines the preferred behavior. This could define prefixes for which the release process is short-circuited. By default this could be empty to force repositories to explicitly opt into the behavior and potentially configure git pre-receive hooks, so the Knope configured commit message format is enforced.

**Comment by dbanty** [comment]
I created #450 to solve this, and then realized that it's not what you were originally asking for 😓. If I understand correctly _now_, you just wanted "there's nothing to release" to not be an error, right?

My general workflow is to manually kick off a release once there is enough stuff to bundle together into a new version—with the feeling that running `knope release` on every commit would create a lot of noise, especially if you try to merge 2 PRs back to back and potentially get conflicts 😨. I wonder if there's a better way to solve for this workflow where you don't want to _manually_ trigger a release, but also don't want extra noise in releases 🤔.

All I can think of right now is a Renovate-style app which bundles commits then auto-merges on a schedule, but that seems heavy handed.

**Comment by BatmanAoD** [comment]
I think that for the purpose of this request, it's not necessary to solve the "noisy releases" problem. It makes sense that the default behavior, which is oriented toward manually creating releases, would error out if there's no release to create, but for integrating Knope into CI, it makes sense to let project maintainers decide whether "there's no release info" to be an error or not. So I think just a new command-line flag would be sufficient here: something like `knope release --allow-no-release`.

**Comment by dbanty** [comment]
`PrepareRelease` now has an `allow_empty` option for letting your `knope` workflow to continue running even if there was nothing to release. Note that you'll have to account for this in any steps within that workflow.

Another option is to use [`continue_on_error`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) in combination with [expressions, like `success()` and `failure()`](https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions) (or the equivalent in non-GitHub Actions CI) to handle this logic _outside_ of Knope.

**Comment by dbanty** [comment]
Also, I started documenting some [recipes](https://knope-dev.github.io/knope/github_actions/github_actions.html) for using Knope in GitHub Actions—if y'all have any different workflows/strategies to share I'd love to see them! It'd be great to document some other CI systems as well.
