### ISSUE TITLE
Breaking change prefix "!" ignored by conventional-git

### ISSUE THREAD

**Issue by erichulburd** [knope-dev/knope#435]
This isn't a problem with knope, but the upstream `git-conventional` crate; I opened an issue for that (https://github.com/crate-ci/git-conventional/issues/39), and am opening an issue here to update git-conventional when/ if there is a solution.

**Comment by dbanty** [comment]
🤔 the `!` definitely works in Knope... we even have [tests for it](https://github.com/knope-dev/knope/blob/af68799983a7c89cd5bc04ed4ee3d672814a299f/src/releases/conventional_commits.rs#L163). Is it maybe just an edge case where it doesn't work?

**Comment by erichulburd** [comment]
Sounds like `breaking_description()` is `None` unless there is a `BREAKING CHANGE:` footer: https://github.com/crate-ci/git-conventional/issues/39#issuecomment-1515526844

Could that be an issue here: https://github.com/knope-dev/knope/blob/2319937a39d19dcfb0bc760e1d7fb939b7d04e2d/src/releases/conventional_commits.rs#L61

**Comment by dbanty** [comment]
Is the test that I linked not actually testing then? It looks like it's asserting that the breaking description is there 🙃

**Comment by erichulburd** [comment]
Sorry, this is my bad *somewhere*; for some reason knope isn't seeing the right commits in my Gitlab pipeline. The last pipeline in question saw _a_ commit, but not the breaking one.

**Comment by erichulburd** [comment]
Ahh, it seems that after merging into the main branch on Gitlab, Knope isn't seeing any commits.

```
$ RUST_LOG=debug knope release
WARNING: The [[packages]] syntax is deprecated, use [package] instead. Run knope --upgrade to do this automatically.
[2023-04-20T19:41:22Z DEBUG knope::git] Processing all commits since tag v0.2.0
[2023-04-20T19:41:22Z DEBUG knope::releases::conventional_commits] Selected commits: []
Error: 
  × Problem with workflow release
Error: step::no_release (https://knope-dev.github.io/knope/config/step/PrepareRelease.html)
  × No packages are ready to release
  help: The `PrepareRelease` step will not complete if no commits cause a
        package's version to be increased.
```

The head of that branch looks like:

```
$ git log --oneline
33bb21a (HEAD -> main, origin/main) Merge branch '***' into 'main'
03f7c0a (origin/***) fix: ***
a172fa8 ci: ***
891e37a ci: ***
d53bdaa (tag: v0.2.0) chore: prepare release 0.2.0 [skip ci]
```

Will follow up once I understand the cause of this.

**Comment by dbanty** [comment]
Wild... I'll admit Git APIs are pretty impossible for me to understand, so it could be there's like... a second type of commit that I'm not looking for? Maybe seeing merge commits requires calling another API.

If you can reproduce in a new repo with a few steps (e.g., tag, commit, make new branch, merge commit, run prepare_release) then we can add that to the integration tests and fix it!

**Comment by erichulburd** [comment]
I've not had time to package a nice script for you, but I can say this - when I configure Gitlab repositories to [fast-forward merge MRs](https://docs.gitlab.com/ee/user/project/merge_requests/methods/#fast-forward-merge), all works great.
