### ISSUE TITLE
Releasing version 1.0

### ISSUE THREAD

**Issue by BatmanAoD** [knope-dev/knope#497]
Is there a way to use Knope to automate a version bump from 0.x to 1.0?

The rules for breaking changes in [the section about 0.x versioning](https://knope-dev.github.io/knope/config/step/BumpVersion.html#a-note-on-0x-versions) make sense, but I don't see anything about how to explicitly request Knope to bump up to version 1.0.0. Is this possible, or does that change need to be made manually?

**Comment by dbanty** [comment]
I haven’t thought of a way to add that because… well no one has released a 1.0 with this yet as far as I know 😅. So it would be manual for that one version for now—but if you have a suggestion for how that feature should work, I’d love to hear it!

**Comment by BatmanAoD** [comment]
I do have one idea, which is to provide a way for manually selecting the next version to assign rather than automatically inferring it. Potentially this capability could be restricted to RC versions, so that you'd be required to create an RC before releasing something that skips a major version or bumps from `0.*` to `1.0`.

I think a command-line flag would be best for this, something like `--assign <version>`, `--next <version>`, or just `--version <version>`. But it could also be restricted to the `CreateChangeFile` step, so that interactivity is required.

**Comment by dbanty** [comment]
This can now be done with `--overide-version`! The first of several issues to fix, thanks for reporting/suggesting them all!
