### ISSUE TITLE
Update & commit `Cargo.lock`

### ISSUE THREAD

**Issue by BatmanAoD** [knope-dev/knope#503]
`Cargo.lock` includes a package reference for the top-level package in a project. This means that when the version number in `Cargo.toml` is updated, the next Cargo build (...or related operation) will update the version in the lockfile.

In repos where `Cargo.lock` is not `.gitignore`d, Knope should do this automatically, so that the tagged release includes the correct version info in `Cargo.lock`.

This should _probably_ be done explicitly using Cargo-edit (or something similar), because I don't know if `cargo build --offline` is guaranteed to always perform the minimal set of updates in this case. (That said, I tried this just now and it seemed to work, so maybe it's an okay approach.)

I realize that having automatic logic to check whether the lockfile is git-ignored complicates this request a bit, but I do think it's probably worthwhile, especially because there's a [recent discussion](https://github.com/rust-lang/cargo/issues/8728#issuecomment-1615331745) on the Cargo project about recommending libraries start checking in lockfiles. One easier-to-implement alternative might be to make this behavior opt-in via some new key in `Knope.toml`.

**Comment by dbanty** [comment]
Related: #162

**Comment by BatmanAoD** [comment]
@dbanty Oops, that looks like a full duplicate to me. Sorry, I searched for existing issues and didn't see that one!
