### ISSUE TITLE
Support versioning Dart packages

### ISSUE THREAD

**Issue by FallenValkyrie** [knope-dev/knope#731]
I've recently found myself wanting to use knope with the Dart language. Dart handles versioning within its `pubspec.yaml`, the documentation for which can be found here:
https://dart.dev/tools/pub/pubspec

**Comment by dbanty** [comment]
Added to 0.13.3, thanks for the suggestion!

**Comment by FallenValkyrie** [comment]
Damn, that was quick.
Thank you very much ^^
