### ISSUE TITLE
Add gitea support

### ISSUE THREAD

**Issue by FallenValkyrie** [knope-dev/knope#743]
Since I'm mainly using gitea and not GitHub, i'd love to see gitea support in Knope.
This should be relatively simple, the documentation for it can be found here: https://try.gitea.io/api/swagger#/repository/repoCreatePullRequest

If there is interest, i would offer myself to implement it. 

Since this is a larger change, I will split this onto 2 PRs:
- [ ] refactor: Making references to github more neutral (using `forge` where we now use `github`)
- [ ] feature: Adding full gitea support

**Comment by dbanty** [comment]
I'd love to support more options than just GitHub, so if you want to give it a shot for the pull request step, go for it!

I think for now we should error if someone defines both `[github]` and `[gitea]`, since it would be unclear where to create the PR. Maybe someday we'll also support multi-repo-projects if someone needs that.

**Comment by FallenValkyrie** [comment]
> I'd love to support more options than just GitHub, so if you want to give it a shot for the pull request step, go for it!
> 
> I think for now we should error if someone defines both `[github]` and `[gitea]`, since it would be unclear where to create the PR. Maybe someday we'll also support multi-repo-projects if someone needs that.

i'd recommend making it a bit more generic. 
since gitea and github are nearly identical in their API logic, my idea was to name it `forge_settings` instead of `github` and skip the logic that would require that error. 

in that case we just add an additional field `type` which can take either `gitea` or `github`
this way we can minimize the logic we would need to add.

for anything that needs split logic, like `state::GitHub` vs `state::Gitea`, we could use a trait and implement that on each state to be able to use dependency injection ^^

**Comment by FallenValkyrie** [comment]
Since this is a larger change, I will split this onto 2 PRs:
- [ ] refactor: Making references to github more neutral (using `forge` where we now use `github`)
- [ ] feature: Adding full gitea support
