### ISSUE TITLE
Disable conventional commits

### ISSUE THREAD

**Issue by ematipico** [knope-dev/knope#924]
I haven't found a way to disable "Conventional commits" in the documentation. 

I wonder if it's something you're open to consider? I am considering using `knope` in my monorepo, although I have a very different semantic versioning flow, so I wonder if "conventional commits" could be disabled to understand the entity of the changes, and use **only** "Change File" to craft a changelog.

**Comment by dbanty** [comment]
We should definitely allow that to be customized, just have to decide on what the config should look like.

You probably want this to be global, right? Rather than having to add it per-package?

**Comment by ematipico** [comment]
> We should definitely allow that to be customized, just have to decide on what the config should look like.
> 
> You probably want this to be global, right? Rather than having to add it per-package?

For my use case, yes, globally. The Knope documentation also advice **not** using CC, and rely on "Change file"

**Comment by dbanty** [comment]
Available now in 0.16.2!
